# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('glutine', models.BooleanField()),
                ('lattosio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordinazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orario_richiesta', models.TimeField()),
                ('orario_cottura', models.TimeField()),
                ('orario_consegna', models.TimeField()),
                ('quantita', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.TimeField()),
                ('fine', models.TimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('prezzo', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pasto',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tavolo'),
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='nome_piatto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Piatto'),
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pasto'),
        ),
        migrations.AddField(
            model_name='composizione',
            name='nome_ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredienti'),
        ),
        migrations.AddField(
            model_name='composizione',
            name='nome_piatto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Piatto'),
        ),
    ]
