# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinazione',
            name='orario_consegna',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordinazione',
            name='orario_cottura',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
