# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170407_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinazione',
            name='nome_piatto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Piatto'),
        ),
    ]
