# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170407_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinazione',
            name='tavolo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Tavolo'),
        ),
    ]
